name: Test Dockerfile
on:
  pull_request:
    paths:
    - "actions.py"
    - "Dockerfile"
    - "drinks.json"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: hadolint Dockerfile
        uses: burdzwastaken/hadolint-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HADOLINT_ACTION_DOCKERFILE_FOLDER: .
